/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("com.text2sql4j.kotlin-common-conventions")

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

val vertxVersion = "4.4.0"

dependencies {
    constraints {
        implementation("io.vertx:vertx-core:$vertxVersion")
        implementation("io.vertx:vertx-lang-kotlin:$vertxVersion")
        implementation("io.vertx:vertx-lang-kotlin-coroutines:$vertxVersion")
        implementation("io.vertx:vertx-web:$vertxVersion")
        implementation("io.vertx:vertx-web-openapi:$vertxVersion")
        implementation("io.vertx:vertx-web-validation:$vertxVersion")
        implementation("io.vertx:vertx-pg-client:$vertxVersion")
        implementation("io.vertx:vertx-sql-client:$vertxVersion")
    }
}