/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("com.text2sql4j.kotlin-common-conventions")

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

val djlVersion = "0.21.0"

dependencies {
    constraints {
        implementation("ai.djl.serving:serving:$djlVersion")
    }

    implementation(platform("ai.djl:bom:$djlVersion"))
}
